// servicesData.js
const servicesData = [
    {
        title: "Internación",
        subservices: [
            "Hospitalización Paciente Crónico Con Ventilador",
            "Hospitalización Paciente Crónico Sin Ventilador",
            "Cuidado Intermedio Neonatal",
            "Cuidado Intermedio Pediátrico",
            "Cuidado Intermedio Adultos",
            "Cuidado Intensivo Neonatal",
            "Cuidado Intensivo Pediátrico",
            "Cuidado Intensivo Adultos",
            "Cuidado Básico Neonatal",
            "Hospitalización Adultos",
            "Hospitalización Pediátrica"
        ]
    },
    {
        title: "Quirurgicos",
        subservices: [
            "Cirugía De Cabeza Y Cuello",
            "Cirugía Cardiovascular",
            "Cirugía General",
            "Cirugía Ginecológica",
            "Cirugía Maxilofacial",
            "Cirugía Oftalmológica",
            "Cirugía Otorrinolaringología",
            "Cirugía Oncológica",
            "Cirugía Oral",
            "Cirugía Pediátrica",
            "Cirugía Plástica Y Estética",
            "Cirugía Plástica Oncológica",
            "Cirugía De Mama Y Tumores Tejidos Blandos",
            "Cirugía Vascular Y Angiológica",
            "Cirugía Urológica",
            "Otras Cirugías",
            "Cirugía Endovascular Neurológica",
            "Cirugía Oncológica Pediátrica",
            "Cirugía De La Mano",
            "Cirugía Dermatológica",
            "Cirugía De Tórax",
            "Cirugía Ortopédica",
            "Cirugía Gastrointestinal",
            "Neurocirugía"
        ]
    },
    {
        title: "consulta Externa",
        subservices: [
            "Anestesia",
            "Cardiología",
            "Cirugía Cardiovascular",
            "Cirugía General",
            "Cirugía Pediátrica",
            "Dolor Y Cuidados Paliativos",
            "Endocrinología",
            "Endodoncia",
            "Enfermería",
            "Estomatología",
            "Gastroenterología",
            "Gastroenterología",
            "Genética",
            "Ginecobstetricia",
            "Hematología",
            "Infectología",
            "Inmunología",
            "Medicina Familiar",
            "Medicina Física Y Rehabilitación",
            "Medicina General",
            "Medicina Interna",
            "Nefrología",
            "Neumología",
            "Neurología",
            "Nutrición Y Dietética",
            "Odontología General",
            "Oncología Clínica",
            "Ortodoncia",
            "Ortopedia Y/O Traumatología",
            "Pediatría",
            "Periodoncia",
            "Psiquiatría",
            "Rehabilitación Oral",
            "Reumatología",
            "Toxicología",
            "Urología",
            "Otras Consultas De Especialidad",
            "Cirugía De Cabeza Y Cuello",
            "Cirugía De Mano",
            "Cirugía De Mama Y Tumores Tejidos Blandos",
            "Cirugía Dermatológica",
            "Cirugía De Tórax",
            "Cirugía Gastrointestinal",
            "Cirugía Ginecológica Laparoscópica",
            "Cirugía Plástica Y Estética",
            "Cirugía Plástica Oncológica",
            "Otras Consultas Generales",
            "Cirugía Vascular",
            "Cirugía Oncológica",
            "Coloproctología",
            "Medicina Nuclear",
            "Nefrología Pediátrica",
            "Neonatología",
            "Neumología Pediátrica",
            "Neurocirugía",
            "Neuropediatría",
            "Oncología Y Hematología Pediátrica",
            "Urología Oncológica",
            "Hematología Oncológica",
            "Radioterapia",
            "Ortopedia Pediátrica",
            "Cirugía Oral",
            "Cirugía Maxilofacial",
            "Vacunación",
        ]
    },
    {
        title: "Apoyo diagnóstico y complementacion terapéutica",
        subservices: [
            "Patología",
            "Gestión Pre-Transfusional",
            "Imágenes Diagnosticas - Ionizantes",
            "Hemodinamia E Intervencionismo",
            "Diagnóstico Vascular",
            "Fisioterapia",
            "Diálisis Peritoneal",
            "Hemodiálisis",
            "Laboratorio De Histotecnología",
            "Terapia Respiratoria",
            "Laboratorio Citologías Cervico-Uterinas",
            "Servicio Farmacéutico",
            "Toma De Muestras De Laboratorio Clínico",
            "Quimioterapia",
            "Laboratorio Clínico",
            "Toma De Muestras De Cuello Uterino Y Ginecológicas",
            "Imágenes Diagnosticas - No Ionizantes",
            "Medicina Nuclear",
            "Radioterapia",
            "Terapia Ocupacional",
            "Fonoaudiología Y/O Terapia Del Lenguaje"
        ]
    },
    {
        title: "Atención Inmediata",
        subservices: [
            "Atención Del Parto",
            "Urgencias",
            "Transporte Asistencial Medicalizado",
            "Atención Prehospitalaria"
        ]
    },
 
];

export default servicesData;